import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import {AuthProvider} from "@/components/AuthContext";
import { verifyAuth } from '@/lib/auth';
import { redirect } from 'next/navigation' ;
import QuizBearBanner from "@/components/QuizBearBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const session = await getServerSession() ; 
  const result = await verifyAuth() ; 

  console.log('result: ' + JSON.stringify(result)) ; 
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider session={session} > */}
        <div className="min-h-screen bg-gradient-to-br from-pink-100 via-yellow-100 to-pink-200" >
        <AuthProvider >
          {result.user ? <div></div> : <NavBar />  }
          {children} 
        </AuthProvider>
        </div>
      </body>
    </html>
  );
}
